### ISSUE TITLE
java.lang.IllegalStateException: Duplicate handle detected. Object to store: NotesNamesList 

### ISSUE THREAD

**Issue by eknori** [klehmann/domino-jna#4]
I am using DirectoryScanner  with 

`int fileType = NotesCAPI.FILE_ANYNOTEFILE + NotesCAPI.FILE_RECURSE;`

in a DOTS tasklet.

when starting DOTS, I get the following error message / stack trace

> java.lang.IllegalStateException: Duplicate handle detected. Object to store: NotesNamesList [handle=422, values=[CN=serv01/O=singultus, serv01, *, */O=singultus, LocalDomainServers, LocalDomainRelays, NotesServers]], object found in open handle list: NotesDatabase [handle=422, server=, filepath=bcc\adt\cgweb.nsf]
	at com.mindoo.domino.jna.gc.NotesGC.__objectCreated(NotesGC.java:45)
	at com.mindoo.domino.jna.utils.NotesNamingUtils.buildNamesList(NotesNamingUtils.java:323)
	at com.mindoo.domino.jna.NotesDatabase.<init>(NotesDatabase.java:212)
	at com.mindoo.domino.jna.NotesDatabase.<init>(NotesDatabase.java:112)
	at com.mindoo.domino.jna.NotesDatabase.<init>(NotesDatabase.java:86)
	at de.eknori.dots.manager.ScannerManager$1$1.entryRead(ScannerManager.java:99)
	at com.mindoo.domino.jna.directory.DirectoryScanner$1.noteFound(DirectoryScanner.java:128)
	at com.mindoo.domino.jna.NotesDatabase$1.invoke(NotesDatabase.java:1486)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:485)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:515)
	at com.sun.jna.Native.invokeInt(Native Method)
	at com.sun.jna.Function.invoke(Function.java:384)
	at com.sun.jna.Function.invoke(Function.java:323)
	at com.sun.jna.Library$Handler.invoke(Library.java:236)
	at com.sun.proxy.$Proxy29.b64_NSFSearch(Unknown Source)
	at com.mindoo.domino.jna.NotesDatabase.search(NotesDatabase.java:1574)
	at com.mindoo.domino.jna.directory.DirectoryScanner.scan(DirectoryScanner.java:52)
	at de.eknori.dots.manager.ScannerManager$1.call(ScannerManager.java:119)
	at com.mindoo.domino.jna.BaseJNA$1.call(BaseJNA.java:60)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:174)
	at com.mindoo.domino.jna.BaseJNA.runWithSession(BaseJNA.java:56)
	at de.eknori.dots.manager.ScannerManager.scanDirectory(ScannerManager.java:79)
	at de.eknori.dots.manager.ScannerManager.run(ScannerManager.java:62)
	at de.eknori.dots.runonstart.ScannerTask$1.doRun(ScannerTask.java:68)
	at de.eknori.dots.runonstart.ScannerTask$1.doRun(ScannerTask.java:63)
	at de.eknori.dots.tools.DominoRunner.runWithSession(DominoRunner.java:89)
	at de.eknori.dots.runonstart.ScannerTask.doRun(ScannerTask.java:63)
	at com.ibm.dots.task.AbstractServerTaskExt.run(AbstractServerTaskExt.java:47)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.doRun(JobTaskService.java:137)
	at com.ibm.dots.task.JobTaskService$ServiceTaskJob.run(JobTaskService.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

All subsequent ( periodic ) runs do not throw an exception.

**Comment by eknori** [comment]
I changed my code from 
`protected void entryRead(SearchResultData data) {
				        if (data instanceof DatabaseData) {
					        dbData = (DatabaseData) data;
					        try {
						        NotesDatabase  db = new NotesDatabase(session, serverName, dbData.getFilePath());
						        String key = DotsUtils.removeSpecialCharacters(`


to 

`protected void entryRead(SearchResultData data) {
				        if (data instanceof DatabaseData) {
					        dbData = (DatabaseData) data;
					        NotesDatabase db = null;
					        try {
						        db = new NotesDatabase(session, serverName, dbData.getFilePath());
						        String key = DotsUtils.removeSpecialCharacters(

// ...

					        } finally {
						        db.recycle();
					        }

`

and this seems to fix the issue. I thought that NotesGC.runWithAutoGC automatically handles the recycle.

**Comment by klehmann** [comment]
I know this intermittent issue. I think the cause is that handles returned by OSMemAlloc do not come from the same memory pool as Domino objects. I commented out the lines that add the NotesNamesList to the auto GC until I can implement a separate auto GC for OSMemAlloc.

**Comment by klehmann** [comment]
I just committed an improved auto GC implementation: 7046cad718fd7a76fd0c9db0026b88ce40516b21

Let me know if this works better.

**Comment by eknori** [comment]
Still the same behaviour.

I am iterating over 10.000 viewEntries

getting the error

`11/04/2016 07:37:28 AM  HTTP JVM: Caused by: java.lang.IllegalStateException: Duplicate handle detected. Object to store: NotesNote [handle=396, noteid=84174], object found in open handle list: NotesDatabase [handle=396, server=, filepath=LotusTraveler_2.nsf]
11/04/2016 07:37:28 AM  HTTP JVM: 	at com.mindoo.domino.jna.gc.NotesGC.__objectCreated(NotesGC.java:94)
11/04/2016 07:37:28 AM  HTTP JVM: 	at com.mindoo.domino.jna.NotesDatabase.openNoteById(NotesDatabase.java:2198)
11/04/2016 07:37:28 AM  HTTP JVM: 	at de.midpoints.travelerrules.dba.DataProviderAPI$1.call(DataProviderAPI.java:74)
11/04/2016 07:37:28 AM  HTTP JVM: 	at com.mindoo.domino.jna.BaseJNA$1.call(BaseJNA.java:60)
11/04/2016 07:37:28 AM  HTTP JVM: 	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:322)
11/04/2016 07:37:28 AM  HTTP JVM: 	at com.mindoo.domino.jna.BaseJNA.runWithSession(BaseJNA.java:56)`

until I explicit do a note.recycle() in the loop

**Comment by eknori** [comment]
with GC debugging ON I get

`[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesNote with handle=39
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Auto-recycling NotesNote [handle=371, noteid=59982]
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesNote with handle=371
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Auto-recycling NotesIDTable [handle=536871852, 0 entries]
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesIDTable with handle=536871852
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Auto-recycling NotesDatabase [handle=397, server=, filepath=LotusTraveler_2.nsf]
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesDatabase with handle=397
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Removing memory: class com.mindoo.domino.jna.NotesNamesList with handle=27
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: AutoGC - Done auto-recycling 345 Domino objects
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: Nov 4, 2016 7:50:51 AM com.vaadin.server.DefaultErrorHandler doDefault
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: SEVERE:
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM: Throwable occurred: java.lang.RuntimeException: java.lang.IllegalStateException: Duplicate handle detected. Object to store: NotesNote [handle=371, noteid=59982], object found in open handle list: NotesCollection [handle=371, noteid=398]
[24B4:000F-25E8] 11/04/2016 07:50:52 AM  HTTP JVM:      at com.mindoo.domino.jna.BaseJNA.runWithSession(BaseJNA.java:66)`

if you wonder about BaseJNA. I use the BaseJNAtest.class as a convenient way to invoke my method

` public class DataProviderAPI extends BaseJNA { ...	

private BeanItemContainer<Device> getDevicesAPI() {
		runWithSession(new IDominoCallable<Object>() {

			@Override
			public Object call(Session session) throws Exception {
				String startPos = "0";
				int entriesToSkip = 1;
				int entriesToReturn = Integer.MAX_VALUE;
				int bufferSize = Integer.MAX_VALUE;
				boolean includeCategoryIds = false;

				System.out.println("getDevicesAPI started ...");
				StopWatch stopWatch = new StopWatch();
				stopWatch.start();`

**Comment by eknori** [comment]
here is the debug out for my code, when i do a note.recycle() in the loop

`[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesNote with handle=39
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Added object: NotesNote [handle=39, noteid=93542]
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesNote with handle=39
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Added object: NotesNote [handle=39, noteid=94534]
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesNote with handle=39
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Auto-recycling 3 Domino objects:
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Auto-recycling NotesCollection [handle=392, noteid=398]
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesIDTable with handle=536871922
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesCollection with handle=392
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Auto-recycling NotesDatabase [handle=397, server=, filepath=LotusTraveler_2.nsf]
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing object: class com.mindoo.domino.jna.NotesDatabase with handle=397
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Removing memory: class com.mindoo.domino.jna.NotesNamesList with handle=41
[24B4:000E-04F8] 11/04/2016 08:12:22 AM  HTTP JVM: AutoGC - Done auto-recycling 3 Domino objects`

**Comment by klehmann** [comment]
I am trying to reproduce this. When I call openNoteById twice with the same note id:

```
NotesNote note = dbData.openNoteById(Integer.parseInt(doc.getNoteID(), 16), EnumSet.noneOf(OpenNote.class));

NotesNote note2 = dbData.openNoteById(Integer.parseInt(doc.getNoteID(), 16), EnumSet.noneOf(OpenNote.class));
```

I get two different handles:
```
AutoGC - Added object: NotesNote [handle=71, noteid=167114]
AutoGC - Added object: NotesNote [handle=73, noteid=167114]
```

Do you have a simple code snippet that I can run to reproduce this?
